name: Github Pipeline

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pipeline"
  pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --tags
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-modules-
            ${{ runner.os }}-
      - name: Install dependencies
        run: yarn install --ignore-scripts --frozen-lockfile
      - name: Set up environment
        run: yarn env dev
      - name: Validate code quality
        run: yarn prettier:check && yarn lint && yarn typescript:check
      - name: Unit testing
        run: yarn test
      - name: Production build
        run: yarn env prod && yarn build

      # NEXT STEPS:
      # - Push build to storage service (eg. S3 in AWS):
      #    aws s3 sync build/ s3://$BUCKET_NAME/ --delete
      # - Invalidate cache in your CDN service (eg. Cloudfront in AWS)
      #    aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
